# Generated by Django 2.2.19 on 2021-05-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='directory_link',
            field=models.URLField(blank=True, default='', verbose_name="Lien Annuaire de l'Education"),
        ),
    ]
