# Generated by Django 2.2.19 on 2021-05-18 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('widgets', '0002_school_directory_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='program_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
