# Generated by Django 2.2.19 on 2021-05-18 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0003_school_program_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='grades',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Diplômes (BAFA/BPJEPS)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qualifications',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Qualifications (PSC1/BTS)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Aucun'), ('DIR.ANIM.', 'Directeur Animation'), ('DIR.F.ANIM.', 'Directrice Animation'), ('ANIM.M', 'Animateur'), ('ANIM.F', 'Animatrice'), ('OFFICE', 'Employé Administratif')], max_length=120),
        ),
        migrations.AlterField(
            model_name='school',
            name='program_end',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Date fin'),
        ),
        migrations.AlterField(
            model_name='school',
            name='program_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Project pédagogique'),
        ),
        migrations.AlterField(
            model_name='school',
            name='program_start',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Date début'),
        ),
    ]
