# Generated by Django 2.2.19 on 2021-04-30 03:09

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='icon_boxes',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='widgets.IconBox'),
        ),
        migrations.AddField(
            model_name='homecarousel',
            name='home',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='home.HomePage'),
        ),
        migrations.AddField(
            model_name='homecarousel',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
