# Generated by Django 2.2.19 on 2021-04-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210430_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoarewepage',
            name='seo_description',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' description. This will appear in head metadata.", max_length=255, verbose_name='page description'),
        ),
        migrations.AddField(
            model_name='whoarewepage',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' keywords. This will appear in head metadata.", max_length=255, verbose_name='page keywords'),
        ),
    ]
