# Generated by Django 2.2.19 on 2021-04-30 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='ChildSignupGuidePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('template', models.CharField(blank=True, default='acm/guide_inscription_page.html', max_length=250)),
            ],
            options={
                'verbose_name': "ACM: Guide d'inscription",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=50, verbose_name='Nom')),
                ('type', models.IntegerField(choices=[(3, 'JEANNE MERTON'), (4, 'EDOUARD MARCEAU')], default=0)),
                ('comment', models.TextField(blank=True, default='', verbose_name='Note additionelle')),
                ('file_drive', models.URLField(blank=True, default='', verbose_name='Lien Google Drive')),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='ProgramsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'ACM: Programmes ACM',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SchoolsAPIPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'ACM: Ecoles API',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SchoolsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'ACM: Ecoles',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TarifsEtHorairesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('template', models.CharField(blank=True, default='acm/tarifs_et_horaires_page.html', max_length=250)),
            ],
            options={
                'verbose_name': 'ACM: Dynamic page for Tarifs or Horaires',
            },
            bases=('wagtailcore.page',),
        ),
    ]
