# Generated by Django 2.2.19 on 2021-05-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acm', '0002_auto_20210430_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='childsignupguidepage',
            name='seo_description',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' description. This will appear in head metadata.", max_length=255, verbose_name='page description'),
        ),
        migrations.AddField(
            model_name='childsignupguidepage',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' keywords. This will appear in head metadata.", max_length=255, verbose_name='page keywords'),
        ),
        migrations.AddField(
            model_name='programspage',
            name='seo_description',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' description. This will appear in head metadata.", max_length=255, verbose_name='page description'),
        ),
        migrations.AddField(
            model_name='programspage',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' keywords. This will appear in head metadata.", max_length=255, verbose_name='page keywords'),
        ),
        migrations.AddField(
            model_name='schoolspage',
            name='seo_description',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' description. This will appear in head metadata.", max_length=255, verbose_name='page description'),
        ),
        migrations.AddField(
            model_name='schoolspage',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' keywords. This will appear in head metadata.", max_length=255, verbose_name='page keywords'),
        ),
    ]
